// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ui} from '../models';

export function Context():Promise<any>;

export function Install(arg1:Array<ui.Application>,arg2:Array<string>,arg3:Array<string>):Promise<void>;

export function Project():Promise<any>;

export function Token():Promise<string>;
