// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListRecipes(arg1:string,arg2:string):Promise<Array<any>>;

export function ListRepositories(arg1:string):Promise<Array<any>>;
