// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Context():Promise<any>;

export function Project():Promise<any>;

export function Token():Promise<string>;
