// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListRecipes(arg1, arg2) {
  return window['go']['ui']['Client']['ListRecipes'](arg1, arg2);
}

export function ListRepositories(arg1) {
  return window['go']['ui']['Client']['ListRepositories'](arg1);
}
