// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Context() {
  return window['go']['ui']['Client']['Context']();
}

export function Project() {
  return window['go']['ui']['Client']['Project']();
}

export function Token() {
  return window['go']['ui']['Client']['Token']();
}
