// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['ui']['Window']['Close']();
}

export function SetClipboard(arg1) {
  return window['go']['ui']['Window']['SetClipboard'](arg1);
}
