FROM ghcr.io/nestybox/ubuntu-jammy-systemd:latest

RUN apt-get -yq update \
  && apt-get -yq install --no-install-recommends \
     apt-transport-https \
     ca-certificates \
     gnupg \
     unzip \
     git \
     openssl \
     curl \
     zsh \
     emacs \
     vim \
     python3 \
     locales-all\
     screen \
     tree \
     less \
     lsb-release \
     openssh-client \
     xz-utils \
     uidmap \
     dbus-user-session \
     iptables \
     kmod \
     fuse-overlayfs \
  && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

RUN useradd -ms /bin/bash plural

WORKDIR /home/plural
ENV XDG_RUNTIME_DIR=/home/plural/.docker
RUN mkdir -p $XDG_RUNTIME_DIR && \
      chown 1000:1000 $XDG_RUNTIME_DIR && \
      echo "kernel.unprivileged_userns_clone=1" >> /etc/sysctl.conf && \
      sysctl --system

USER plural
#ENV DOCKER_VERSION=24.0.0
#RUN apt-get -yq update && apt-get install -y curl && rm -rf /var/lib/apt/lists/* \    && curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh \
#RUN curl -fsSL https://get.docker.com/rootless -o get-docker.sh && sh get-docker.sh --version ${DOCKER_VERSION} && usermod -a -G docker plural
ENV SKIP_IPTABLES=1
RUN curl -fsSL https://get.docker.com/rootless -o get-docker.sh && sh get-docker.sh 
#&& usermod -a -G docker plural
ADD https://raw.githubusercontent.com/docker/docker-ce/master/components/cli/contrib/completion/bash/docker /etc/bash_completion.d/docker.sh


## Install Docker
#RUN apt-get update && apt-get install -y curl \
#    && rm -rf /var/lib/apt/lists/* \
#    && curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh \
#    # Add user "admin" to the Docker group
#    && usermod -a -G docker admin
#ADD https://raw.githubusercontent.com/docker/docker-ce/master/components/cli/contrib/completion/bash/docker /etc/bash_completion.d/docker.sh
#
## Install Sshd
#RUN apt-get update && apt-get install --no-install-recommends -y openssh-server \
#    && rm -rf /var/lib/apt/lists/* \
#    && mkdir /home/admin/.ssh \
#    && chown admin:admin /home/admin/.ssh

EXPOSE 22

USER root

# Set systemd as entrypoint.
ENTRYPOINT [ "/sbin/init", "--log-level=err" ]